# Generated by Django 4.2.14 on 2024-07-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passed_tests_number',
            field=models.IntegerField(default=0),
        ),
    ]
