# Generated by Django 4.2.14 on 2024-07-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_passed_tests_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='colors',
            field=models.ManyToManyField(to='users.color'),
        ),
    ]
