# Generated by Django 4.2.14 on 2024-07-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_rename_questionanswer_rightanswer_and_more'),
        ('users', '0005_user_passed_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passed_tests',
        ),
        migrations.AddField(
            model_name='user',
            name='answers',
            field=models.ManyToManyField(to='quizzes.answer'),
        ),
    ]
