# Generated by Django 4.2.14 on 2024-07-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_color_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passed_tests_number',
        ),
        migrations.AlterField(
            model_name='color',
            name='value',
            field=models.CharField(default='rgba(255,255,255,1)', max_length=64),
        ),
    ]
