# Generated by Django 4.2.14 on 2024-07-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_rename_price_question_points'),
        ('users', '0009_alter_user_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='answers',
            field=models.ManyToManyField(blank=True, to='quizzes.answer'),
        ),
    ]
