# Generated by Django 4.2.14 on 2024-07-19 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.color'),
        ),
    ]
