# Generated by Django 4.2.14 on 2024-07-21 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('users', '0011_alter_user_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='shop.color'),
        ),
        migrations.AlterField(
            model_name='user',
            name='colors',
            field=models.ManyToManyField(to='shop.color'),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
