# Generated by Django 4.2.14 on 2024-07-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, unique=True, verbose_name='Color name')),
                ('value', models.CharField(default='rgba(255,255,255,1)', max_length=64)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
