# Generated by Django 4.2.14 on 2024-07-17 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_rename_questionanswer_rightanswer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rightanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.answer'),
        ),
    ]
