# Generated by Django 4.2.14 on 2024-07-17 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_alter_rightanswer_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.answer')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer', to='quizzes.question')),
            ],
        ),
        migrations.DeleteModel(
            name='RightAnswer',
        ),
        migrations.AddConstraint(
            model_name='correctanswer',
            constraint=models.UniqueConstraint(fields=('question', 'answer'), name='correct_answers'),
        ),
    ]
