# Generated by Django 4.2.14 on 2024-07-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_correctanswer_delete_rightanswer_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='correctanswer',
            name='correct_answers',
        ),
        migrations.AddConstraint(
            model_name='correctanswer',
            constraint=models.UniqueConstraint(fields=('question', 'answer'), name='unique_correct_answers'),
        ),
    ]
